ServisVozila/Controllers/UslugeController.cs
using ServisVozila.Misc;
using ServisVozila.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace ServisVozila.Controllers
{
 

    public class UslugeController : Controller
    {
      


        BazaDbContext bazaPodataka = new BazaDbContext();
        [AllowAnonymous]
        public ActionResult Index()
        {
            return View();
        }


        [AllowAnonymous]
        public ActionResult PopisUsluga()
        {
            var kvar = bazaPodataka.PopisUsluga.ToList();

            return View(kvar);
           
        }


        [OverrideAuthorization]
        [Authorize]
        public ActionResult Brisi(string id)
        {
            if (id == null)

            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            kvar k = bazaPodataka.PopisUsluga.Find(id);
            if (k == null)
            {
                return HttpNotFound();
               
            }
            return View(k);
        }

        [HttpPost, ActionName("Brisi")]
        [Authorize ]
        public ActionResult BrisiStatus(string id)
        {
            kvar k = bazaPodataka.PopisUsluga.Find(id);
            bazaPodataka.PopisUsluga.Remove(k);
            bazaPodataka.SaveChanges();
            return View("PopisUsluga");
        }

      



    }
}

ServisVozila/Views/Usluge/Brisi.cshtml
@using ServisVozila.Models
@model kvar
@{
    ViewBag.Title = "Briši";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2> @ViewBag.Title</h2>



<strong>Jeste li sigurni da želite obrisati uslugu @Model.nazivKvar (ID: @Model.idKvar)?</strong>

<br />
<br />
@using (Html.BeginForm("Brisi", "Usluge"))
{
    @Html.AntiForgeryToken();
    <button type="submit" class="btn btn-danger">
        <span class="glyphicon glyphicon-ok" aria-hidden="false">
        </span>
        Izbriši
    </button>

    <br />
    <br />

    @Html.ActionLink("Odustani", "PopisUsluga", "Usluge", new { @class = "btn btn-info btn-sm" });
}

ServisVozila/Views/Usluge/BrisiStatus.cshtml
@{
    ViewBag.Title = "Brisanje usluge";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="alert alert-success" role="alert">Student uspješno obrisan!</div>

@Html.ActionLink("Povratak na popis usluga", "PopisUsluga", "Usluge", new { @class = "btn btn-info btn-sm" })

ServisVozila/Views/Usluge/PopisUsluga.cshtml
@using ServisVozila.Models
@using ServisVozila.Misc
@model List<kvar>
@{
    ViewBag.Title = "PopisUsluga";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Popis naših usluga</h2>
<br/>
<table id="customers" border="1">
    <tr>

        <th>ID</th>
        <th>Naziv</th>
        <th>Sati potrebni</th>
        <th>Cijena</th>
        @if (User.Identity.IsAuthenticated && (User as LogiraniKorisnik).IsInRole(OvlastiKorisnik.Administrator))
        {
            <th>Izbriši</th>
        }

    </tr>
    @foreach (var kvar in Model)
    {
<tr>
    <td>@kvar.idKvar</td>
    <td>@kvar.nazivKvar</td>
    <td>@kvar.satiPotrebni</td>
    <td>@kvar.cijenaKvar</td>

    @if (User.Identity.IsAuthenticated && (User as LogiraniKorisnik).IsInRole(OvlastiKorisnik.Administrator))
    {
        <td> <center/> @Html.ActionLink("Izbriši", "Brisi", new { id = kvar.idKvar }, new { @class = "btn btn-danger btn-sm" })</td>
    }

</tr>
    }
</table>