ServisVozila/Controllers/KlijentiController.cs
using ServisVozila.Misc;
using ServisVozila.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace ServisVozila.Controllers
{
    [Authorize(Roles = OvlastiKorisnik.Administrator)]

    public class KlijentiController : Controller
    {
        BazaDbContext bazaPodataka = new BazaDbContext();
        public ActionResult Index()
        {
            return View();
        }


        public ActionResult PopisKlijenata(string prezime)
        {
            var klijent = bazaPodataka.PopisKlijenata.ToList();

            if (!String.IsNullOrWhiteSpace(prezime))
            {
                klijent = klijent.Where(x => x.prezime.ToUpper().Contains(prezime.ToUpper())).ToList();
            }




            return View(klijent);
        }
        public ActionResult Detalji(int? id)
        {
            if (!id.HasValue)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            Klijenti klijent = bazaPodataka.PopisKlijenata.FirstOrDefault(x => x.id == id);

            if (klijent == null)
            {
                return HttpNotFound();
            }
            return View(klijent);
        }

        public ActionResult Azuriraj(int? id)
        {
            Klijenti klijenti = null;
            if (!id.HasValue)
            {
                klijenti = new Klijenti();
                ViewBag.Title = "Kreiranje klijenta";
                ViewBag.Novi = true;
                
            }
            else
            {
                klijenti = bazaPodataka.PopisKlijenata
                    .FirstOrDefault(k => k.id == id);

                if (klijenti == null)
                {
                    return HttpNotFound();
                }

                ViewBag.Title = "Ažuriranje postojećeg klijenta";
                ViewBag.Novi = false;
            }

            var kvar = bazaPodataka.PopisUsluga.OrderBy(x => x.nazivKvar).ToList();
            kvar.Insert(0, new kvar { idKvar = "", nazivKvar = "Nedefinirano" });
            ViewBag.Usluge=kvar;

            var automobil = bazaPodataka.PopisAutomobila.OrderBy(x => x.idAutomobil).ToList();
            automobil.Insert(0, new Automobil { idAutomobil = "Nedefinirano", modelVozila = "Nedefinirano", markaVozila="Audi", bojaVozila = "Nedefinirano", brojSasije= "Nedefinirano", godProizvodnje=DateTime.Now, kilometri=0, regTablice= "Nedefinirano" });
            ViewBag.Automobil = automobil;

            return View(klijenti);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Azuriraj(Klijenti k)
        {
            if (ModelState.IsValid)
            {
                if (k.id != 0)
                    bazaPodataka.Entry(k).State = System.Data.Entity.EntityState.Modified;
                else
                    bazaPodataka.PopisKlijenata.Add(k);
                bazaPodataka.SaveChanges();

                return RedirectToAction("PopisKlijenata");
            }

            if (k.id != 0)
            {
                ViewBag.Title = "Ažuriranje klijenta";
                ViewBag.Novi = false;
               
            }
            else
            {
                ViewBag.Title = "Kreiranje novog klijenta";
              
                ViewBag.Novi = true;
            }
            var kvar = bazaPodataka.PopisUsluga.OrderBy(x => x.nazivKvar).ToList();
            kvar.Insert(0, new kvar { idKvar = "", nazivKvar = "Nedefinirano" });
            ViewBag.Usluge = kvar;

            var automobil = bazaPodataka.PopisAutomobila.OrderBy(x => x.idAutomobil).ToList();
            automobil.Insert(0, new Automobil { idAutomobil = "Nedefinirano", modelVozila = "Nedefinirano", markaVozila = "Audi", bojaVozila = "Nedefinirano", brojSasije = "Nedefinirano", godProizvodnje = DateTime.Now, kilometri = 0, regTablice = "Nedefinirano" });
            ViewBag.Automobil = automobil;


            return View(k);
        }

        public ActionResult Brisi(int? id)
        {
            if (id == null)
                return RedirectToAction("PopisKlijenata");
            Klijenti k = bazaPodataka.PopisKlijenata.FirstOrDefault(x => x.id == id);
            if (k == null)
                return HttpNotFound();
            ViewBag.Title = "Potvrda brisanja klijenta";
            return View(k);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Brisi(int id)
        {
            Klijenti s = bazaPodataka.PopisKlijenata
                .FirstOrDefault(x => x.id == id);
            if (s == null)
                return HttpNotFound();
            bazaPodataka.PopisKlijenata.Remove(s);
            bazaPodataka.SaveChanges();
            return View("BrisiStatus");
        }


        public ActionResult Automobil(string id)
        {
            if (id==null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            Automobil automobil = bazaPodataka.PopisAutomobila.FirstOrDefault(x => x.idAutomobil == id);

            if (automobil == null)
            {
                return HttpNotFound();
            }
            return View(automobil);
        }

        public ActionResult DetaljiOKvaru(string id)
        {
            if (id==null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            kvar k = bazaPodataka.PopisUsluga.FirstOrDefault(x => x.idKvar == id);

            if (k == null)
            {
                return HttpNotFound();
            }
            return View(k);
        }






    }
}

ServisVozila/Controllers/PocetnaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ServisVozila.Controllers
{
    public class PocetnaController : Controller
    {
       [AllowAnonymous]
        public ActionResult Pocetna()
        {
            ViewBag.Title = "VBL Servis vozila";
            ViewBag.Message = "Čakovec";
            ViewBag.Description = "S vama od 2020.";
            return View();
        }
        [AllowAnonymous]
        public ActionResult Onama()
        {
            ViewBag.Title = "O nama";
            return View();
        }


        [AllowAnonymous]
        public ActionResult Kontakt()
        {
            ViewBag.Title = "Kontakt";
            return View();
        }
        [AllowAnonymous]
        public ActionResult RadnoVrijeme()
        {
            ViewBag.Title = "Radno vrijeme";
            return View();
        }

    }
}

ServisVozila/Controllers/RadnikController.cs
using ServisVozila.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Net;
using System.Web.Mvc;
using ServisVozila.Misc;

namespace ServisVozila.Controllers
{
    [Authorize(Roles = OvlastiKorisnik.Administrator)]

    public class RadnikController : Controller
    {
        BazaDbContext bazaPodataka = new BazaDbContext();
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult PopisRadnika()
        {
            var radnik = bazaPodataka.PopisRadnika.ToList();

            return View(radnik);
        }

        public ActionResult Detalji(int? id)
        {
            if (!id.HasValue)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            radnik radnici = bazaPodataka.PopisRadnika.FirstOrDefault(x => x.idRadnik == id);

            if (radnici == null)
            {
                return HttpNotFound();
            }
            return View(radnici);
        }


        public ActionResult Brisi(int? id)
        {
            if (id == null)
                return RedirectToAction("PopisRadnika");
            radnik r = bazaPodataka.PopisRadnika.FirstOrDefault(x => x.idRadnik == id);
            if (r == null)
                return HttpNotFound();
            ViewBag.Title = "Potvrda brisanja radnika";
            return View(r);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Brisi(int id)
        {
            radnik ra = bazaPodataka.PopisRadnika
                .FirstOrDefault(x => x.idRadnik == id);
            if (ra == null)
                return HttpNotFound();
            bazaPodataka.PopisRadnika.Remove(ra);
            bazaPodataka.SaveChanges();
            return View("BrisiStatus");
        }


        public ActionResult DetaljiOOdjelu(int? id)
        {
            if (!id.HasValue)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            odjel o = bazaPodataka.PopisOdjela.FirstOrDefault(x => x.idOdjel == id);

            if (o == null)
            {
                return HttpNotFound();
            }
            return View(o);
        }




        public ActionResult Azuriraj(int? id)
        {
            radnik r = null;
            if (!id.HasValue)
            {
                r = new radnik();
                ViewBag.Title = "Kreiranje radnika";
                ViewBag.Novi = true;

            }
            else
            {
                r = bazaPodataka.PopisRadnika
                    .FirstOrDefault(k => k.idRadnik == id);

                if (r == null)
                {
                    return HttpNotFound();
                }

                ViewBag.Title = "Ažuriranje postojećeg radnika";
                ViewBag.Novi = false;
            }



            return View(r);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Azuriraj(radnik r)
        {
            if (ModelState.IsValid)
            {
                if (r.idRadnik != 0)

                    bazaPodataka.Entry(r).State = System.Data.Entity.EntityState.Modified;

                else
                    bazaPodataka.PopisRadnika.Add(r);
                bazaPodataka.SaveChanges();
                return RedirectToAction("PopisRadnika");
            }

            if (r.idRadnik != 0)
            {
                ViewBag.Title = "Ažuriranje radnika";
                ViewBag.Novi = false;

            }
            else
            {
                ViewBag.Title = "Kreiranje novog radnika";

                ViewBag.Novi = true;
            }
            return View(r);
        }




    }
}

ServisVozila/Views/Shared/_Layout.cshtml
@using ServisVozila.Misc

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - VBL Servis Vozila</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <style>
        body {
            background-color: lightgray;
        }
        </style>
        <div class="navbar navbar-inverse navbar-fixed-top" >
        <div class="container" >
        <div class="navbar-header" >
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" >
        <span class="icon-bar" > </span >
        <span class="icon-bar" > </span >
        <span class="icon-bar" > </span >
        </button >

        </div >
        <div class="navbar-collapse collapse" >
        <ul class="nav navbar-nav navbar-left" >
        <li >@Html.ActionLink("Naslovnica", "Pocetna", "Pocetna") </li >
        <li >@Html.ActionLink("O nama", "Onama", "Pocetna") </li >
        <li >@Html.ActionLink("Usluge", "PopisUsluga", "Usluge") </li >
        <li >@Html.ActionLink("Kontakt", "Kontakt", "Pocetna") </li >
        <li >@Html.ActionLink("Radno vrijeme", "RadnoVrijeme", "Pocetna") </li >
        @if (User.Identity.IsAuthenticated && (User as LogiraniKorisnik).IsInRole(OvlastiKorisnik.Administrator))
                    {
                         <li >@Html.ActionLink("Popis klijenata", "PopisKlijenata", "Klijenti") </li >
                         <li >@Html.ActionLink("Popis radnika", "PopisRadnika", "Radnik") </li >
                         <li >@Html.ActionLink("Korisnici", "PopisKorisnika", "Korisnici") </li >
                    }
        </ul >
        <ul class="nav navbar-nav navbar-right" >
        <li >@Html.ActionLink("Registracija", "Registracija", "Korisnici") </li >

        </ul >


        <ul class="nav navbar-nav navbar-right" >
        @if (User.Identity.IsAuthenticated)
                        {
                             <li >@Html.ActionLink(((User as LogiraniKorisnik).PrezimeIme), "Pocetna", "Pocetna") </li >
                             <li >@Html.ActionLink("Odjava", "Odjava", "Korisnici") </li >
                        }
                        else
                        {
                             <li >@Html.ActionLink("Prijava", "Prijava", "Korisnici") </li >
                        }
        </ul >


        </div >
        </div >
        </div >
        <div class="container body-content" >
        @RenderBody()
        <hr / >
        <footer >
        <p > &copy; VBL Servis vozila @DateTime.Now.Year </p >
        </footer >
        </div >
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
        </body >
        </html >